/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties.new'
import { Route as AuthenticatedAdminBrainsRouteImport } from './routes/_authenticated/admin.brains'
import { Route as AuthenticatedPropertiesIdIndexRouteImport } from './routes/_authenticated/properties.$id.index'
import { Route as ApiPublicReportsTokenRouteImport } from './routes/api/public/reports/$token'
import { Route as AuthenticatedPropertiesIdReviewRouteImport } from './routes/_authenticated/properties.$id.review'
import { Route as AuthenticatedPropertiesIdPhotosRouteImport } from './routes/_authenticated/properties.$id.photos'
import { Route as AuthenticatedPropertiesIdItemsNewRouteImport } from './routes/_authenticated/properties.$id.items.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBrainsRoute =
  AuthenticatedAdminBrainsRouteImport.update({
    id: '/admin/brains',
    path: '/admin/brains',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIdIndexRoute =
  AuthenticatedPropertiesIdIndexRouteImport.update({
    id: '/properties/$id/',
    path: '/properties/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicReportsTokenRoute = ApiPublicReportsTokenRouteImport.update({
  id: '/api/public/reports/$token',
  path: '/api/public/reports/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesIdReviewRoute =
  AuthenticatedPropertiesIdReviewRouteImport.update({
    id: '/properties/$id/review',
    path: '/properties/$id/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIdPhotosRoute =
  AuthenticatedPropertiesIdPhotosRouteImport.update({
    id: '/properties/$id/photos',
    path: '/properties/$id/photos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIdItemsNewRoute =
  AuthenticatedPropertiesIdItemsNewRouteImport.update({
    id: '/properties/$id/items/new',
    path: '/properties/$id/items/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/brains': typeof AuthenticatedAdminBrainsRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/properties/$id/photos': typeof AuthenticatedPropertiesIdPhotosRoute
  '/properties/$id/review': typeof AuthenticatedPropertiesIdReviewRoute
  '/api/public/reports/$token': typeof ApiPublicReportsTokenRoute
  '/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
  '/properties/$id/items/new': typeof AuthenticatedPropertiesIdItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/brains': typeof AuthenticatedAdminBrainsRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/properties/$id/photos': typeof AuthenticatedPropertiesIdPhotosRoute
  '/properties/$id/review': typeof AuthenticatedPropertiesIdReviewRoute
  '/api/public/reports/$token': typeof ApiPublicReportsTokenRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdIndexRoute
  '/properties/$id/items/new': typeof AuthenticatedPropertiesIdItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/brains': typeof AuthenticatedAdminBrainsRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/properties/$id/photos': typeof AuthenticatedPropertiesIdPhotosRoute
  '/_authenticated/properties/$id/review': typeof AuthenticatedPropertiesIdReviewRoute
  '/api/public/reports/$token': typeof ApiPublicReportsTokenRoute
  '/_authenticated/properties/$id/': typeof AuthenticatedPropertiesIdIndexRoute
  '/_authenticated/properties/$id/items/new': typeof AuthenticatedPropertiesIdItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/brains'
    | '/properties/new'
    | '/properties/$id/photos'
    | '/properties/$id/review'
    | '/api/public/reports/$token'
    | '/properties/$id/'
    | '/properties/$id/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/brains'
    | '/properties/new'
    | '/properties/$id/photos'
    | '/properties/$id/review'
    | '/api/public/reports/$token'
    | '/properties/$id'
    | '/properties/$id/items/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/brains'
    | '/_authenticated/properties/new'
    | '/_authenticated/properties/$id/photos'
    | '/_authenticated/properties/$id/review'
    | '/api/public/reports/$token'
    | '/_authenticated/properties/$id/'
    | '/_authenticated/properties/$id/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicReportsTokenRoute: typeof ApiPublicReportsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/brains': {
      id: '/_authenticated/admin/brains'
      path: '/admin/brains'
      fullPath: '/admin/brains'
      preLoaderRoute: typeof AuthenticatedAdminBrainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id/': {
      id: '/_authenticated/properties/$id/'
      path: '/properties/$id'
      fullPath: '/properties/$id/'
      preLoaderRoute: typeof AuthenticatedPropertiesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/reports/$token': {
      id: '/api/public/reports/$token'
      path: '/api/public/reports/$token'
      fullPath: '/api/public/reports/$token'
      preLoaderRoute: typeof ApiPublicReportsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties/$id/review': {
      id: '/_authenticated/properties/$id/review'
      path: '/properties/$id/review'
      fullPath: '/properties/$id/review'
      preLoaderRoute: typeof AuthenticatedPropertiesIdReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id/photos': {
      id: '/_authenticated/properties/$id/photos'
      path: '/properties/$id/photos'
      fullPath: '/properties/$id/photos'
      preLoaderRoute: typeof AuthenticatedPropertiesIdPhotosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id/items/new': {
      id: '/_authenticated/properties/$id/items/new'
      path: '/properties/$id/items/new'
      fullPath: '/properties/$id/items/new'
      preLoaderRoute: typeof AuthenticatedPropertiesIdItemsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminBrainsRoute: typeof AuthenticatedAdminBrainsRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedPropertiesIdPhotosRoute: typeof AuthenticatedPropertiesIdPhotosRoute
  AuthenticatedPropertiesIdReviewRoute: typeof AuthenticatedPropertiesIdReviewRoute
  AuthenticatedPropertiesIdIndexRoute: typeof AuthenticatedPropertiesIdIndexRoute
  AuthenticatedPropertiesIdItemsNewRoute: typeof AuthenticatedPropertiesIdItemsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminBrainsRoute: AuthenticatedAdminBrainsRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedPropertiesIdPhotosRoute: AuthenticatedPropertiesIdPhotosRoute,
  AuthenticatedPropertiesIdReviewRoute: AuthenticatedPropertiesIdReviewRoute,
  AuthenticatedPropertiesIdIndexRoute: AuthenticatedPropertiesIdIndexRoute,
  AuthenticatedPropertiesIdItemsNewRoute:
    AuthenticatedPropertiesIdItemsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicReportsTokenRoute: ApiPublicReportsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
